import 'dart:async';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:speech_to_text/speech_recognition_result.dart';
import 'package:speech_to_text/speech_to_text.dart';

import '../../core/providers/model_provider.dart';
import '../../core/services/inference_service.dart';
import '../../core/services/performance_service.dart';
import '../../core/services/tts_service.dart';
import '../../core/theme/nomad_theme.dart';
import '../../core/widgets/nomad_animations.dart';

/// Nomad Voice — full-screen voice conversation mode.
///
/// Loop:
///   `idle → listening (STT) → thinking (LLM) → speaking (TTS) → listening`
///
/// Everything runs locally: speech_to_text uses the platform's on-device
/// recognizer when available, the response is generated by the selected
/// local model via `InferenceService`, and flutter_tts speaks the answer
/// back through the system TTS engine.
class VoiceScreen extends ConsumerStatefulWidget {
  const VoiceScreen({super.key});

  @override
  ConsumerState<VoiceScreen> createState() => _VoiceScreenState();
}

enum _VoiceState { idle, listening, thinking, speaking, unavailable }

class _VoiceScreenState extends ConsumerState<VoiceScreen>
    with TickerProviderStateMixin {
  late final AnimationController _orbController;
  late final AnimationController _entryController;

  final SpeechToText _stt = SpeechToText();
  final TtsService _tts = TtsService();

  _VoiceState _state = _VoiceState.idle;
  bool _muted = false;
  bool _ready = false;
  String _caption = 'Tap the orb to start speaking';
  String _transcript = '';
  String _assistantText = '';

  final List<Map<String, String>> _history = [];
  StreamSubscription<String>? _llmSubscription;

  @override
  void initState() {
    super.initState();
    _orbController = AnimationController(
      vsync: this,
      duration: const Duration(seconds: 6),
    );
    // The orb's always-on phase loop drives a CustomPainter that fills the
    // orb rect every frame. Same treatment as the aurora backdrops: on
    // constrained devices we drop the loop entirely so the saved layer is
    // painted once and the frame budget is preserved for the audio-reactive
    // ripple that fires when the user speaks.
    if (!PerformanceService.instance.isConstrained) {
      _orbController.repeat();
    }
    _entryController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 520),
    )..forward();
    _initEngines();
  }

  Future<void> _initEngines() async {
    try {
      final available = await _stt.initialize(
        onStatus: _onSttStatus,
        onError: (e) {
          if (!mounted) return;
          setState(() {
            _state = _VoiceState.idle;
            _caption = 'Speech error — tap to try again';
          });
        },
      );

      _tts.setMuted(_muted);

      if (!mounted) return;
      setState(() {
        _ready = available;
        if (!available) {
          _state = _VoiceState.unavailable;
          _caption = 'Voice not available on this device';
        }
      });
    } catch (_) {
      if (!mounted) return;
      setState(() {
        _state = _VoiceState.unavailable;
        _caption = 'Voice not available on this device';
      });
    }
  }

  void _onSttStatus(String status) {
    // Statuses: "listening", "notListening", "done"
    // Note: _finalizeAndAsk is called from _onResult when finalResult is true
    // to avoid duplicate calls
    if (!mounted) return;
  }

  @override
  void dispose() {
    _orbController.dispose();
    _entryController.dispose();
    _llmSubscription?.cancel();
    _stt.stop();
    _tts.stop();
    super.dispose();
  }

  Future<void> _startListening() async {
    if (!_ready || _muted) return;
    HapticFeedback.mediumImpact();
    setState(() {
      _state = _VoiceState.listening;
      _caption = 'Listening…';
      _transcript = '';
    });
    await _tts.stop();
    await _stt.listen(
      onResult: _onResult,
      listenOptions: SpeechListenOptions(
        partialResults: true,
        cancelOnError: true,
        listenMode: ListenMode.confirmation,
        listenFor: const Duration(minutes: 1),
        pauseFor: const Duration(seconds: 2),
      ),
    );
  }

  void _onResult(SpeechRecognitionResult r) {
    if (!mounted) return;
    setState(() {
      _transcript = r.recognizedWords;
      _caption = _transcript.isEmpty ? 'Listening…' : _transcript;
    });
    if (r.finalResult) {
      _finalizeAndAsk();
    }
  }

  Future<void> _finalizeAndAsk() async {
    if (_state != _VoiceState.listening) return;
    await _stt.stop();
    final question = _transcript.trim();
    if (question.isEmpty) {
      if (!mounted) return;
      setState(() {
        _state = _VoiceState.idle;
        _caption = 'Tap the orb to try again';
      });
      return;
    }
    await _askModel(question);
  }

  Future<void> _askModel(String prompt) async {
    final model = ref.read(selectedModelProvider);
    if (model == null || model.localPath == null) {
      if (!mounted) return;
      setState(() {
        _state = _VoiceState.idle;
        _caption =
            'No local model selected. Download one from Models to use Nomad Voice.';
      });
      return;
    }

    setState(() {
      _state = _VoiceState.thinking;
      _caption = 'Thinking…';
      _assistantText = '';
    });

    _history.add({'role': 'user', 'content': prompt});

    final buffer = StringBuffer();
    final spokenIndex = ValueNotifier<int>(0);
    final stream = InferenceService().streamChat(
      modelId: model.id,
      prompt: prompt,
      localPath: model.localPath,
      systemPrompt:
          "You are Nomad, a warm, witty, and genuinely caring voice companion. "
          "Speak like a real person chatting with a friend — natural, relaxed, and easy to listen to. "
          "Use contractions and a casual rhythm, keep it to 1–3 short sentences, and let a little personality and warmth come through. "
          "Never use markdown, bullets, lists, or code — just spoken-style words.",
      history: _history.length > 1
          ? _history.sublist(0, _history.length - 1)
          : const [],
      maxTokens: 256,
    );

    bool startedSpeaking = false;

    _llmSubscription = stream.listen(
      (chunk) async {
        buffer.write(chunk);
        if (!mounted) return;
        setState(() {
          _assistantText = buffer.toString();
          if (!startedSpeaking) {
            _state = _VoiceState.speaking;
            _caption = _assistantText;
            startedSpeaking = true;
          } else {
            _caption = _assistantText;
          }
        });
        // Speak whenever a sentence boundary appears.
        await _speakNewSentences(buffer.toString(), spokenIndex);
      },
      onError: (_) {
        if (!mounted) return;
        setState(() {
          _state = _VoiceState.idle;
          _caption = 'Something went wrong. Tap the orb to retry.';
        });
      },
      onDone: () async {
        final text = buffer.toString().trim();
        if (text.isNotEmpty) {
          _history.add({'role': 'assistant', 'content': text});
          // Speak the remainder.
          final remaining = text.substring(spokenIndex.value).trim();
          if (remaining.isNotEmpty) {
            await _tts.speak(remaining);
          }
        }
        if (!mounted) return;
        setState(() {
          _state = _VoiceState.idle;
          _caption = 'Tap the orb to continue';
        });
      },
    );
  }

  Future<void> _speakNewSentences(
      String full, ValueNotifier<int> spokenIndex) async {
    // Find the last sentence boundary up to which we can safely speak.
    final pending = full.substring(spokenIndex.value);
    final lastBoundary = _lastSentenceBoundary(pending);
    if (lastBoundary <= 0) return;
    final chunk = pending.substring(0, lastBoundary).trim();
    spokenIndex.value += lastBoundary;
    if (chunk.isEmpty) return;
    await _tts.speak(chunk);
  }

  int _lastSentenceBoundary(String s) {
    var last = -1;
    for (int i = 0; i < s.length; i++) {
      final c = s[i];
      if (c == '.' || c == '?' || c == '!' || c == '\n') {
        last = i + 1;
      }
    }
    return last;
  }

  Future<void> _interrupt() async {
    HapticFeedback.lightImpact();
    _llmSubscription?.cancel();
    await _tts.stop();
    await _stt.stop();
    if (!mounted) return;
    setState(() {
      _state = _VoiceState.idle;
      _caption = 'Tap the orb to start speaking';
    });
  }

  void _onOrbTap() {
    switch (_state) {
      case _VoiceState.idle:
        _startListening();
        break;
      case _VoiceState.listening:
        _finalizeAndAsk();
        break;
      case _VoiceState.thinking:
      case _VoiceState.speaking:
        _interrupt();
        break;
      case _VoiceState.unavailable:
        break;
    }
  }

  void _toggleMute() {
    HapticFeedback.selectionClick();
    setState(() => _muted = !_muted);
    _tts.setMuted(_muted);
    if (_muted) {
      _stt.stop();
      if (_state == _VoiceState.listening) {
        setState(() {
          _state = _VoiceState.idle;
          _caption = 'Muted';
        });
      }
    }
  }

  void _endSession() {
    HapticFeedback.lightImpact();
    _interrupt();
    context.pop();
  }

  @override
  Widget build(BuildContext context) {
    final nomad = Theme.of(context).extension<NomadColorsExtension>()!;
    final brightness = Theme.of(context).brightness;
    final textTheme = Theme.of(context).textTheme;

    return AnnotatedRegion<SystemUiOverlayStyle>(
      value: SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
        statusBarIconBrightness:
            brightness == Brightness.dark ? Brightness.light : Brightness.dark,
      ),
      child: Scaffold(
        backgroundColor: nomad.background,
        body: SafeArea(
          child: Column(
            children: [
              Padding(
                padding:
                    const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                child: Row(
                  children: [
                    _CircleIconButton(
                      onTap: () => context.pop(),
                      icon: Icons.close_rounded,
                      tooltip: 'Close voice mode',
                    ),
                    const Spacer(),
                    Text(
                      'Nomad Voice',
                      style: textTheme.titleMedium?.copyWith(
                        color: nomad.textSecondary,
                        letterSpacing: 0.4,
                      ),
                    ),
                    const Spacer(),
                    const SizedBox(width: 44),
                  ],
                ),
              ),
              Expanded(
                child: Center(
                  child: GestureDetector(
                    onTap: _onOrbTap,
                    behavior: HitTestBehavior.opaque,
                    child: AnimatedBuilder(
                      animation: Listenable.merge(
                        [_orbController, _entryController],
                      ),
                      builder: (context, _) {
                        final entryT = _entryController.value;
                        return Transform.scale(
                          scale: 0.85 + 0.15 * entryT,
                          child: Opacity(
                            opacity: entryT,
                            child: _VoiceOrb(
                              t: _orbController.value,
                              state: _state,
                              primary: nomad.accent,
                              secondary: nomad.accentWarm,
                              bg: nomad.background,
                            ),
                          ),
                        );
                      },
                    ),
                  ),
                ),
              ),
              Padding(
                padding:
                    const EdgeInsets.symmetric(horizontal: 32, vertical: 8),
                child: ConstrainedBox(
                  constraints: const BoxConstraints(minHeight: 64),
                  child: AnimatedSwitcher(
                    duration: const Duration(milliseconds: 240),
                    switchInCurve: Curves.linear,
                    switchOutCurve: Curves.linear,
                    child: Text(
                      _caption,
                      key: ValueKey(_caption),
                      textAlign: TextAlign.center,
                      maxLines: 4,
                      overflow: TextOverflow.ellipsis,
                      style: textTheme.titleLarge?.copyWith(
                        color: nomad.textPrimary,
                        height: 1.35,
                      ),
                    ),
                  ),
                ),
              ),
              Padding(
                padding: EdgeInsets.fromLTRB(
                  24,
                  16,
                  24,
                  24 + MediaQuery.of(context).padding.bottom * 0.5,
                ),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                  children: [
                    _PillButton(
                      icon: _muted ? Icons.mic_off_rounded : Icons.mic_rounded,
                      label: _muted ? 'Unmute' : 'Mute',
                      onTap: _toggleMute,
                      isActive: _muted,
                    ),
                    _PillButton(
                      icon: Icons.keyboard_rounded,
                      label: 'Keyboard',
                      onTap: () => context.pop(),
                    ),
                    _PillButton(
                      icon: Icons.call_end_rounded,
                      label: 'End',
                      onTap: _endSession,
                      destructive: true,
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _VoiceOrb extends StatelessWidget {
  final double t;
  final _VoiceState state;
  final Color primary;
  final Color secondary;
  final Color bg;

  const _VoiceOrb({
    required this.t,
    required this.state,
    required this.primary,
    required this.secondary,
    required this.bg,
  });

  @override
  Widget build(BuildContext context) {
    const size = 240.0;
    return SizedBox.square(
      dimension: size + 60,
      child: Stack(
        alignment: Alignment.center,
        children: [
          _OrbHalo(t: t, state: state, color: primary, size: size + 40),
          ClipOval(
            child: CustomPaint(
              size: const Size.square(size),
              painter: _OrbPainter(
                t: t,
                state: state,
                primary: primary,
                secondary: secondary,
                bg: bg,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _OrbHalo extends StatelessWidget {
  final double t;
  final _VoiceState state;
  final Color color;
  final double size;
  const _OrbHalo({
    required this.t,
    required this.state,
    required this.color,
    required this.size,
  });

  @override
  Widget build(BuildContext context) {
    final amp = switch (state) {
      _VoiceState.idle => 0.04,
      _VoiceState.listening => 0.12,
      _VoiceState.thinking => 0.06,
      _VoiceState.speaking => 0.16,
      _VoiceState.unavailable => 0.0,
    };
    final phase = (state == _VoiceState.speaking ? 2.4 : 1.0) * t * 2 * math.pi;
    final scale = 1.0 + amp * math.sin(phase);
    final alpha = state == _VoiceState.idle ? 0.18 : 0.32;
    return Transform.scale(
      scale: scale,
      child: Container(
        width: size,
        height: size,
        decoration: BoxDecoration(
          shape: BoxShape.circle,
          gradient: RadialGradient(
            colors: [
              color.withValues(alpha: alpha),
              color.withValues(alpha: 0),
            ],
          ),
        ),
      ),
    );
  }
}

class _OrbPainter extends CustomPainter {
  final double t;
  final _VoiceState state;
  final Color primary;
  final Color secondary;
  final Color bg;

  _OrbPainter({
    required this.t,
    required this.state,
    required this.primary,
    required this.secondary,
    required this.bg,
  });

  @override
  void paint(Canvas canvas, Size size) {
    final center = size.center(Offset.zero);
    final radius = size.shortestSide / 2;

    final basePaint = Paint()
      ..shader = RadialGradient(
        colors: [
          Color.lerp(primary, secondary, 0.35)!,
          Color.lerp(primary, bg, 0.55)!,
        ],
        stops: const [0.0, 1.0],
      ).createShader(Rect.fromCircle(center: center, radius: radius));
    canvas.drawCircle(center, radius, basePaint);

    final freq = state == _VoiceState.speaking ? 3.0 : 1.3;
    for (int i = 0; i < 3; i++) {
      final phase = t * 2 * math.pi * freq + i * (2 * math.pi / 3);
      final dx = math.cos(phase) * radius * 0.35;
      final dy = math.sin(phase * 0.9) * radius * 0.30;
      final blobRadius = radius * (0.55 + 0.08 * math.sin(phase * 0.7));
      final paint = Paint()
        ..shader = RadialGradient(
          colors: [
            (i.isEven ? secondary : primary).withValues(alpha: 0.55),
            primary.withValues(alpha: 0),
          ],
        ).createShader(
          Rect.fromCircle(center: center + Offset(dx, dy), radius: blobRadius),
        )
        ..blendMode = BlendMode.plus;
      canvas.drawCircle(center + Offset(dx, dy), blobRadius, paint);
    }

    final rim = Paint()
      ..color = Colors.white.withValues(alpha: 0.10)
      ..style = PaintingStyle.stroke
      ..strokeWidth = 1.5;
    canvas.drawCircle(center, radius - 1, rim);

    if (state == _VoiceState.listening || state == _VoiceState.speaking) {
      final rippleT = (t * 2) % 1.0;
      final rippleRadius = radius * (0.7 + 0.35 * rippleT);
      final rippleAlpha = (1.0 - rippleT) * 0.6;
      final ripple = Paint()
        ..color = (state == _VoiceState.speaking ? secondary : primary)
            .withValues(alpha: rippleAlpha)
        ..style = PaintingStyle.stroke
        ..strokeWidth = 2.0;
      canvas.drawCircle(center, rippleRadius, ripple);
    }
  }

  @override
  bool shouldRepaint(covariant _OrbPainter old) =>
      old.t != t ||
      old.state != state ||
      old.primary != primary ||
      old.secondary != secondary;
}

class _CircleIconButton extends StatelessWidget {
  final VoidCallback onTap;
  final IconData icon;
  final String tooltip;

  const _CircleIconButton({
    required this.onTap,
    required this.icon,
    required this.tooltip,
  });

  @override
  Widget build(BuildContext context) {
    final nomad = Theme.of(context).extension<NomadColorsExtension>()!;
    return Tooltip(
      message: tooltip,
      child: BouncyTap(
        onTap: onTap,
        scaleDown: 0.9,
        child: Container(
          width: 44,
          height: 44,
          decoration: BoxDecoration(
            color: nomad.surface.withValues(alpha: 0.9),
            shape: BoxShape.circle,
            border: Border.all(color: nomad.border, width: 1),
          ),
          child: Icon(icon, size: 20, color: nomad.textPrimary),
        ),
      ),
    );
  }
}

class _PillButton extends StatelessWidget {
  final IconData icon;
  final String label;
  final VoidCallback onTap;
  final bool isActive;
  final bool destructive;

  const _PillButton({
    required this.icon,
    required this.label,
    required this.onTap,
    this.isActive = false,
    this.destructive = false,
  });

  @override
  Widget build(BuildContext context) {
    final nomad = Theme.of(context).extension<NomadColorsExtension>()!;
    final textTheme = Theme.of(context).textTheme;
    final bg = destructive
        ? Colors.red.withValues(alpha: 0.12)
        : (isActive
            ? nomad.textPrimary.withValues(alpha: 0.12)
            : nomad.surface.withValues(alpha: 0.9));
    final fg = destructive ? Colors.red : nomad.textPrimary;
    return BouncyTap(
      onTap: onTap,
      scaleDown: 0.92,
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Container(
            width: 60,
            height: 60,
            decoration: BoxDecoration(
              color: bg,
              shape: BoxShape.circle,
              border: Border.all(
                color: destructive
                    ? Colors.red.withValues(alpha: 0.3)
                    : nomad.border,
                width: 1,
              ),
            ),
            child: Icon(icon, size: 24, color: fg),
          ),
          const SizedBox(height: 8),
          Text(
            label,
            style: textTheme.labelLarge?.copyWith(
              color: destructive ? Colors.red : nomad.textSecondary,
            ),
          ),
        ],
      ),
    );
  }
}
